baseURL = ''
languageCode = 'en-us'
title = 'Portfolio Website'
theme = 'hugo-resume'
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
 

[params]
address = "Tempe, AZ"
email = "jacob_dominski@yahoo.com"
favicon = "/favicon.ico"
firstName = "Jacob"
lastName = "Dominski"
phone = "1-480-440-9135"
profileImage = "img/profilepic.jpg"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = true
showPublications = false
showQr = false
showSkills = true


[[params.handles]]
link = "https://www.linkedin.com/in/jacob-dominski-825149200/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/jacobdominski/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"